import type { BoardDocument } from './model/board-document.schema'

export function serializeBoardDiagnostics(document: BoardDocument): string {
  return JSON.stringify({
    documentRevision: document.documentRevision,
    camera: document.camera,
    frames: document.frames.map(({
      id,
      x,
      y,
      width,
      height,
      aspectRatio,
      revision,
      captureHash,
      screenshotPath,
      kind,
      lifeState,
      unitId,
      zoneId,
      liveSource,
      kit,
    }) => ({
      id,
      x,
      y,
      width,
      height,
      aspectRatio,
      revision,
      captureHash,
      screenshotPath,
      kind,
      lifeState,
      unitId,
      zoneId: zoneId ?? null,
      artifactHash: liveSource?.artifactHash ?? null,
      kitState: kit?.state ?? null,
    })),
    annotations: document.annotations.map(({
      id,
      frameId,
      instruction,
      anchor,
      mark,
      madeAgainstCaptureHash,
      madeAgainstRevision,
    }) => ({
      id,
      frameId,
      instruction,
      anchor,
      mark,
      madeAgainstCaptureHash,
      madeAgainstRevision,
    })),
    units: document.units.map(({ id, state, nomineeFrameId, lockedFrameId, dependsOnUnitIds }) => ({
      id,
      state,
      nomineeFrameId: nomineeFrameId ?? null,
      lockedFrameId: lockedFrameId ?? null,
      dependsOnUnitIds,
    })),
    zones: document.zones.map(({ id, unitId, kind, collapsed }) => ({ id, unitId, kind, collapsed })),
    verdicts: document.verdicts.map(({ id, unitId, frameId, kind, summary, kitSnapshot }) => ({
      id,
      unitId,
      frameId,
      kind,
      summary,
      kitSnapshot: kitSnapshot ?? null,
    })),
  })
}
